[package]
name = "matryx_client"
version = "0.1.0"
edition = "2024"

[lints.rust]
warnings = "warn"

[dependencies]

matryx_entity = { path = "../entity" }
matryx_surrealdb = { path = "../surrealdb" }

reqwest = { version = "0.12", features = ["json", "stream"] }
urlencoding = "2.1"
tokio = { version = "1.47.1", features = ["full"] }
serde = "1.0.228"
serde_json = "1.0.145"
chrono = "0.4.42"
uuid = "1.18.1"
thiserror = "2.0.16"
anyhow = "1.0.100"
async-stream = "0.3.6"
tracing = "0.1.41"
futures = "0.3.31"
tokio-tungstenite = "0.28"
url = "2.5"
base64 = "0.22.1"
futures-util = "0.3.31"
tokio-stream = { version = "0.1.17", features = ["sync"] }
surrealdb = { path = "../../forks/surrealdb/crates/sdk" }

[lib]
name = "matryx_client"
path = "src/lib.rs"
