[workspace]
resolver = "2"
members = [
    "packages/client",
    "packages/entity", 
    "packages/server",
    "packages/surrealdb",
]
exclude = ["tmp", "docs", "forks"]

[workspace.lints.rust]
warnings = "warn"
