[package]
name = "matryx_surrealdb"
version = "0.1.0"
edition = "2024"
description = "SurrealDB Data Access Object layer for MaxTryX Matrix client/server with SurrealDB LIVE queries"

[lints]
workspace = true

[dependencies]

matryx_entity = { path = "../entity" }

# Database
surrealdb = { path = "../../forks/surrealdb/crates/sdk", features = ["kv-mem", "kv-surrealkv"], version = "3.0.0" }

# Async runtime
tokio = { version = "1", features = ["full"] }
futures = "0.3.31"
futures-util = "0.3.31"
async-stream = "0.3.6"
async-channel = "2.3.1"

# Caching
moka = { version = "0.12.10", features = ["future"] }

# Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1"
base64 = "0.22.1"

# Logging & error handling
tracing = "0.1.41"
thiserror = "2.0.16"
anyhow = "1.0.99"

# Time utilities
chrono = { version = "0.4.41", features = ["serde"] }
uuid = "1.18.0"
async-trait = "0.1.89"
tokio-stream = "0.1.17"

# Cryptography and random
sha2 = "0.10.8"
rand = "0.8.5"
ed25519-dalek = "2.1.1"


[dev-dependencies]
serial_test = "3"
tempfile = "3"
tracing-subscriber = "0.3.19"

[lib]
name = "matryx_surrealdb"
path = "src/lib.rs"
