[package]
name = "matryx"
version = "0.1.0"
edition = "2024"

[features]
default = ["desktop"]
desktop = ["dep:notify-rust"]

[dependencies]
anyhow = "1.0"
bitflags = "^2.9"
chrono = "0.4"
clap = {version = "~4.5", features = ["derive"]}
css-color-parser = "0.1.2"
dirs = "6.0.0"
emojis = "0.7"
futures = "0.3"
gethostname = "1"
html5ever = "0.35"
image = "0.25"
libc = "0.2"
markup5ever_rcdom = "0.3.0"
mime = "^0.3.17"
mime_guess = "^2.0.5"
nom = "8.0.0"
open = "5.3.2"
rand = "0.9"
ratatui = { version = "0.30.0-alpha.5", features = [] }
ratatui-image = { version = "8", features = ["serde"] }
regex = "^1.11"
rpassword = "^7.3"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
sled = "0.34.7"
temp-dir = "0.1"
thiserror = "2"
toml = "^0.8.20"
tracing = "~0.1.41"
tracing-appender = "~0.2.3"
tracing-subscriber = "0.3.19"
unicode-segmentation = "^1.12"
unicode-width = "0.2"
url = {version = "^2.5.4", features = ["serde"]}
edit = "0.1.5"
humansize = "2.1.3"
surrealdb-migrations = "2"
crossterm = "0.29"
clipboard = "0.5.0"
syntect = "5.2.0"
lazy_static = "1.5.0"
matryx_api = { path = "../api" }
uuid = "1.18"
hex = "0.4.3"
base64 = "0.22.1"
surrealdb = { path = "../../forks/surrealdb/crates/sdk", features = ["kv-surrealkv"] }
surrealdb-core = { path = "../../forks/surrealdb/crates/core", default-features = false }
include_dir = "0.7.4"

[dependencies.comrak]
version = "0.41"
default-features = false
features = ["shortcodes"]

[dependencies.notify-rust]
version = "~4.11.6"
default-features = false
features = ["zbus", "serde"]
optional = true

# Removed modalkit dependencies



[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt-multi-thread", "sync", "time"]

[dev-dependencies]
lazy_static = "1.5.0"
pretty_assertions = "1.4.1"
tempfile = "3"



[build-dependencies]
vergen = { version = "9", features = ["build", "time"] }

[package.metadata.deb]
section = "net"
license-file = ["LICENSE", "0"]
assets = [
    # Binary:
    ["target/release/maxtryx", "usr/bin/maxtryx", "755"],
    # Manual pages:
    ["docs/maxtryx.1", "usr/share/man/man1/maxtryx.1", "644"],
    ["docs/maxtryx.5", "usr/share/man/man5/maxtryx.5", "644"],
    # Other assets:
    ["maxtryx.desktop", "usr/share/applications/maxtryx.desktop", "644"],
    ["config.example.toml", "usr/share/maxtryx/config.example.toml", "644"],
    ["docs/maxtryx.svg", "usr/share/icons/hicolor/scalable/apps/maxtryx.svg", "644"],
    ["docs/maxtryx.metainfo.xml", "usr/share/metainfo/maxtryx.metainfo.xml", "644"],
]

[package.metadata.generate-rpm]
assets = [
    # Binary:
    { source = "target/release/maxtryx", dest = "/usr/bin/maxtryx", mode = "755" },
    # Manual pages:
    { source = "docs/maxtryx.1", dest = "/usr/share/man/man1/maxtryx.1", mode = "644" },
    { source = "docs/maxtryx.5", dest = "/usr/share/man/man5/maxtryx.5", mode = "644" },
    # Other assets:
    { source = "maxtryx.desktop", dest = "/usr/share/applications/maxtryx.desktop", mode = "644" },
    { source = "config.example.toml", dest = "/usr/share/maxtryx/config.example.toml", mode = "644"},
    { source = "docs/maxtryx.svg", dest = "/usr/share/icons/hicolor/scalable/apps/maxtryx.svg", mode = "644"},
    { source = "docs/maxtryx.metainfo.xml", dest = "/usr/share/metainfo/maxtryx.metainfo.xml", mode = "644"},
]

[[bin]]
path = "src/main.rs"
name = "maxtryx"
