[package]
name = "matryx_entity"
version = "0.1.0"
edition = "2021"
description = "Pure Matrix protocol entity types and data structures"



[dependencies]
# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# Time utilities
chrono = { version = "0.4.42", features = ["serde"] }

# Cryptography
bcrypt = "0.17.1"

# Error handling
thiserror = "2.0.16"

# URL utilities
url = { version = "2.5", features = ["serde"] }

[lib]
name = "matryx_entity"
path = "src/lib.rs"
