[package]
name = "matryx_entity"
version = "0.1.0"
edition = "2021"
description = "Pure Matrix protocol entity types and data structures"



[dependencies]
# Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"

# Time utilities
chrono = { version = "0.4.41", features = ["serde"] }

# Cryptography
bcrypt = "0.17.1"

[lib]
name = "matryx_entity"
path = "src/lib.rs"