[package]
name = "matryx_api"
version = "0.1.0"
edition = "2024"
authors = ["David Maple<david@cyrup.ai>"]
description = "Matrix SDK integration"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cyrup-ai/maxtryx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async runtime
tokio = { version = "1.47.1", features = ["full"] }
futures = "0.3.31"
async-stream = "0.3.6"

# Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1"
base64 = "0.22.1"

# Logging & error handling
tracing = "0.1.41"
thiserror = "2.0.16"
anyhow = "1.0.99"

# Time utilities
chrono = { version = "0.4.41", features = ["serde"] }

# Matrix SDK
matrix-sdk-base = "0.13"
matrix-sdk = "0.13"
matrix-sdk-crypto = "0.13"

# Database
surrealdb = { path = "../../forks/surrealdb/crates/sdk", features = ["kv-surrealkv"] }
# UUID generation
uuid = { version = "1.18.0", features = ["v4", "serde"] }

# Other
growable-bloom-filter = "2.1.1"
surrealdb-migrations = { git = "https://github.com/Odonno/surrealdb-migrations.git", branch = "main" }
include_dir = "0.7.4"
once_cell = "1.21.3"
tokio-stream = "0.1.17"
serde_yaml = { version = "0.9.34", default-features = false }
hex = "0.4.3"
futures-util = "0.3.31"
mime = "0.3.17"
async-trait = "0.1.89"

[dev-dependencies]
serial_test = "3"
tempfile = "3"

[lib]
name = "matryx_api"
path = "src/lib.rs"

[[test]]
name = "integration"
path = "tests/integration/main.rs"
