[package]
name = "matryx_server"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]

matryx_entity = { path = "../entity" }
matryx_surrealdb = { path = "../surrealdb" }

axum = { version = "0.8.4", features = ["ws", "multipart"] }
chrono = "0.4.42"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1"
uuid = "1.18.1"
tower-http = { version = "0.6.6", features = ["cors"] }
tracing-subscriber = "0.3.20"
jsonwebtoken = "9.3.1"
thiserror = "2.0.16"
anyhow = "1.0.100"
async-session = "3.0"
axum-extra = { version = "0.10", features = ["cookie", "typed-header"] }
tower = "0.5.2"
tower-cookies = "0.11"
surrealdb = { path = "../../forks/surrealdb/crates/sdk", features = ["kv-surrealkv"] }
bcrypt = "0.17.1"
tracing = "0.1.41"
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
vodozemac = "0.9.0"
reqwest = { version = "0.12", features = ["json", "native-tls", "stream"] }
rand = "0.9.2"
rand_core = "0.9"
getrandom = "0.3"
base64 = "0.22.1"
futures = "0.3.31"
sha2 = "0.10.9"
aes = "0.8.4"
cbc = "0.1.2"
hmac = "0.12.1"
hkdf = "0.12.4"
regex = "1.11"
urlencoding = "2.1.3"
tokio-cron-scheduler = "0.14.0"
tantivy = "0.25.0"
unicode-normalization = "0.1.24"
unicode-segmentation = "1.12.0"
hickory-resolver = "0.25"
ruma-html = "0.5.0"
once_cell = "1.21.3"
image = { version = "0.25.8", features = ["png", "jpeg", "gif", "webp"] }
subtle = "2.6.1"
lettre = { version = "0.11.18", default-features = false, features = ["builder", "hostname", "smtp-transport", "tokio1-rustls-tls"] }
moka = { version = "0.12.11", features = ["future"] }
tokio-util = "0.7.16"
url = "2.5"
http-body = "1.0.1"
governor = "0.10.1"
prometheus = "0.14.0"
lazy_static = "1.5.0"
async-trait = "0.1.89"
async-stream = "0.3.6"
httpdate = "1.0"
# Add certificate parsing capability
x509-parser = "0.18"

[dev-dependencies]
mockall = "0.13"
tokio-test = "0.4"
wiremock = "0.6"
rstest = "0.26"
http = "1.3"
axum-test = "18.1.0"
matrix-sdk = "0.14"
tempfile = "3.23"
url = "2.5"
assign = "1.1.1"

[[bin]]
path = "src/main.rs"
name = "matryxd"
