name: Matrix Compliance Testing

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  compliance:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
          
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev
          
      - name: Install SyTest dependencies
        run: |
          sudo apt-get install -y perl cpanminus
          git clone https://github.com/matrix-org/sytest.git /tmp/sytest
          cd /tmp/sytest && ./install-deps.pl || true
          
      - name: Check code formatting
        run: cargo fmt --all -- --check
        
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        
      - name: Build project
        run: cargo build --release
        
      - name: Run unit tests
        run: cargo test --lib
        
      - name: Run integration tests
        run: cargo test --test integration --package matryx_server
        env:
          TEST_TIMEOUT_SECONDS: 60
          TEST_MAX_CONCURRENT_USERS: 5
          TEST_ENABLE_FEDERATION: true
          TEST_ENABLE_PERFORMANCE: true
          
      - name: Run compliance tests
        run: cargo test --test compliance --package matryx_server
        env:
          TEST_TIMEOUT_SECONDS: 120
          
      - name: Run performance tests
        run: cargo test --test performance --package matryx_server
        env:
          TEST_MAX_CONCURRENT_USERS: 3
          TEST_TIMEOUT_SECONDS: 180